import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://images.pexels.com/photos/6567673/pexels-photo-6567673.jpeg?auto=compress&cs=tinysrgb&w=600" ,
    title: "Crown, Veil and Earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    color: "silver",
    category: "earrings",
  },
  {
    img: "https://images.pexels.com/photos/2735981/pexels-photo-2735981.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Diamond Ring",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    color: "gold",
    category: "rings",
  },

  {
    img: "https://images.pexels.com/photos/2849742/pexels-photo-2849742.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Ring with Blossom",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    color: "silver",
    category: "rings",
  },
  {
    img: "https://images.pexels.com/photos/3214241/pexels-photo-3214241.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Silver-colored Earring",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    color: "silver",
    category: "earrings",
  },
  {
    img: "https://images.pexels.com/photos/12026053/pexels-photo-12026053.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Silver and Gold Necklace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    color: "gold",
    category: "necklace",
  },
  {
    img: "https://images.pexels.com/photos/2965095/pexels-photo-2965095.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "White Pearl Earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    color: "white",
    category: "earrings",
  },

  {
    img: "https://images.pexels.com/photos/10983783/pexels-photo-10983783.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Pearl Earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    color: "white",
    category: "earrings",
  },

  {
    img: "https://images.pexels.com/photos/15446125/pexels-photo-15446125/free-photo-of-photo-of-womans-chest-covered-in-glitter.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Heart pendent",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    color: "gold",
    category: "pendents",
  },

  {
    img: "https://images.pexels.com/photos/266621/pexels-photo-266621.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Gemstones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    color: "white",
    category: "bracelets",
  },

  {
    img: "https://images.pexels.com/photos/1446161/pexels-photo-1446161.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Bridal Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    color: "gold",
    category: "bridal set",
  },
  {
    img: "https://images.pexels.com/photos/1454171/pexels-photo-1454171.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Gold Necklace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    color: "gold",
    category: "necklace",
  },
  {
    img: "https://images.pexels.com/photos/3266700/pexels-photo-3266700.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Gold Earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    color: "gold",
    category: "earrings",
  },
  {
    img: "https://images.pexels.com/photos/1927260/pexels-photo-1927260.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Ring in a Box",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    color: "white",
    category: "rings",
  },
  {
    img: "https://images.pexels.com/photos/1454185/pexels-photo-1454185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Red Stone pendal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    color: "red",
    category: "pendents",
  },

  {
    img: "https://images.pexels.com/photos/730055/pexels-photo-730055.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Wedding Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    color: "gold",
    category: "bridal set",
  },
  {
    img: "https://images.pexels.com/photos/2673365/pexels-photo-2673365.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Bridal Gold",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    color: "gold",
    category: "bridal set",
  },
  {
    img: "https://images.pexels.com/photos/6858599/pexels-photo-6858599.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Black Gemstone Pendant",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    color: "gold",
    category: "pendents",
  },
  {
    img: "https://images.pexels.com/photos/2879829/pexels-photo-2879829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Silver Coloured Bracelet",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    color: "silver",
    category: "bracelets",
  },
  {
    img: "https://images.pexels.com/photos/12290109/pexels-photo-12290109.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Diamond Bracelet",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    color: "white",
    category: "bracelets",
  },
  {
    img: "https://images.pexels.com/photos/3641059/pexels-photo-3641059.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Gold and Diamond Jewelry",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    color: "gold  ",
    category: "heels",
  },
];

export default data;
